{{-- CORRECTED: Updated timeline.blade.php with ORIGINAL styles/CSS and only logic changes --}}




<div class="container-fluid px-0">
    <div class="row">
        <div class="col-12">
            <div class="timeline-section">
                <!-- Project Overview Header -->
                <div class="project-overview">
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <h3 class="mb-1">{{ $job->name }}</h3>
                            <div class="job-meta">
                                <span class="badge bg-{{ $job->status === 'pending' ? 'warning' : ($job->status === 'in_progress' ? 'primary' : ($job->status === 'completed' ? 'success' : 'secondary')) }}">
                                    {{ ucfirst(str_replace('_', ' ', $job->status)) }}
                                </span>
                            </div>
                        </div>
                        <div class="col-md-4 text-end">
                            <div class="progress-circle">
                                <div class="progress-text">{{ $jobStats['overall_progress'] }}%</div>
                            </div>
                        </div>
                    </div>
                </div>

                @if($timelineData['tasks'] && count($timelineData['tasks']) > 0)
                    <!-- UPDATED: Date Range Controls - Now defaults to full job timeline -->
                    <div class="date-controls mb-3">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <div class="d-flex gap-2 align-items-center">
                                    <label class="form-label mb-0 fw-bold">View:</label>
                                    <input type="date" class="form-control form-control-sm" id="startDate"
                                           value="{{ $timelineData['timeline_start'] ? $timelineData['timeline_start']->format('Y-m-d') : ($job->start_date ? $job->start_date->format('Y-m-d') : date('Y-m-d')) }}" style="width: auto;">
                                    <span class="text-muted">to</span>
                                    <input type="date" class="form-control form-control-sm" id="endDate"
                                           value="{{ $timelineData['timeline_end'] ? $timelineData['timeline_end']->format('Y-m-d') : ($job->due_date ? $job->due_date->format('Y-m-d') : date('Y-m-d', strtotime('+30 days'))) }}" style="width: auto;">
                                    <button class="btn btn-primary btn-sm" onclick="updateDateRange()">Update</button>
                                </div>
                            </div>
                            <div class="col-md-6 text-end">
                                <div class="btn-group btn-group-sm">
                                    <button class="btn btn-outline-secondary" onclick="setQuickRange('week')">This Week</button>
                                    <button class="btn btn-outline-secondary" onclick="setQuickRange('month')">This Month</button>
                                    <button class="btn btn-outline-secondary active" onclick="setQuickRange('job')">Full Job</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Timeline Chart -->
                    <div class="timeline-chart">
                        <div class="timeline-scroll-container">
                            <div class="timeline-header">
                                <div class="timeline-labels">Tasks</div>
                                <div class="timeline-dates-container">
                                    <div class="timeline-dates" id="timelineDates">
                                        <!-- Dates generated by JS -->
                                    </div>
                                </div>
                            </div>

                            <!-- Scrollable Container for Task Rows -->
                            <div class="timeline-content">
                                <!-- Task Rows -->
                                @foreach($timelineData['tasks'] as $task)
                                    <div class="timeline-row" onclick="selectTask({{ $task['id'] }})" data-task-id="{{ $task['id'] }}">
                                        <div class="task-label">
                                            <div class="task-info">
                                                @php
                                                    $statusIcons = [
                                                        'completed' => 'fas fa-check-circle text-success',
                                                        'in_progress' => 'fas fa-play-circle text-primary',
                                                        'pending' => 'fas fa-clock text-warning',
                                                        'cancelled' => 'fas fa-times-circle text-danger'
                                                    ];
                                                @endphp
                                                <i class="{{ $statusIcons[$task['status']] ?? 'fas fa-circle text-secondary' }} me-2"></i>
                                                <div>
                                                    <div class="task-name">{{ $task['name'] }}</div>
                                                    <div class="task-users">
                                                        {{ implode(', ', array_column($task['users']->toArray(), 'name')) }}
                                                    </div>
                                                    <!-- ORIGINAL: Duration styling -->
                                                    <div class="task-duration text-muted small">
                                                        <i class="fas fa-clock me-1"></i>
                                                        {{ $task['formatted_duration'] ?? 'Not set' }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="task-timeline-container">
                                            <div class="task-timeline">
                                                @php
                                                    $barClass = match($task['status']) {
                                                        'completed' => 'task-completed',
                                                        'in_progress' => 'task-progress',
                                                        'pending' => 'task-pending',
                                                        default => 'task-pending'
                                                    };
                                                @endphp
                                                <!-- UPDATED: Task bar positioning uses ORIGINAL task dates -->
                                                <div class="task-bar {{ $barClass }}"
                                                     data-start="{{ $task['start_date_time'] ? $task['start_date_time']->format('Y-m-d') : '' }}"
                                                     data-end="{{ $task['end_date_time'] ? $task['end_date_time']->format('Y-m-d') : '' }}"
                                                     data-start-time="{{ $task['start_date_time'] ? $task['start_date_time']->format('H:i') : '' }}"
                                                     data-end-time="{{ $task['end_date_time'] ? $task['end_date_time']->format('H:i') : '' }}">
                                                    <div class="task-content">
                                                        {{ $task['progress'] }}%
                                                        @if($task['has_extension_request'])
                                                            <div class="extension-badge">!</div>
                                                        @endif
                                                        <!-- ORIGINAL: Time indicators -->
                                                        @if($task['start_date_time'])
                                                            <div class="time-indicator start-time">S</div>
                                                        @endif
                                                        @if($task['end_date_time'])
                                                            <div class="time-indicator end-time">E</div>
                                                        @endif
                                                    </div>
                                                    <!-- ORIGINAL: Progress fill based on actual progress -->
                                                    <div class="progress-fill" style="width: {{ $task['progress'] }}%"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>

                    <!-- Scroll Instructions -->
                    <div class="alert alert-info alert-sm mt-3" id="scrollInstructions" style="display: none;">
                        <i class="fas fa-info-circle me-1"></i>
                        Use horizontal scroll or drag to navigate the timeline.
                    </div>

                    <!-- Task Details Panel -->
                    <div class="task-details" id="taskDetails" style="display: none;">
                        <div class="row">
                            <div class="col-md-8">
                                <h6 id="taskName" class="text-dark fw-bold">Task Details</h6>
                                <p id="taskDescription" class="text-muted mb-3">Select a task to view details</p>

                                <div class="row">
                                    <div class="col-md-6">
                                        <strong>Timeline:</strong><br>
                                        <span id="taskTimeline">-</span>
                                    </div>
                                    <div class="col-md-6">
                                        <strong>Progress:</strong><br>
                                        <div class="progress">
                                            <div class="progress-bar" id="taskProgressBar" style="width: 0%"></div>
                                        </div>
                                        <small id="taskProgressText">0%</small>
                                    </div>
                                </div>

                                <!-- ORIGINAL: Duration details -->
                                <div class="row mt-3">
                                    <div class="col-md-6">
                                        <strong>Planned Duration:</strong><br>
                                        <span id="taskPlannedDuration">-</span>
                                    </div>
                                    <div class="col-md-6">
                                        <strong>Time Remaining:</strong><br>
                                        <span id="taskTimeRemaining">-</span>
                                    </div>
                                </div>
                            </div>

                            <div class="mt-3">
                                <strong>Assigned Users:</strong>
                                <div id="taskUsers" class="mt-2">
                                    <!-- Populated by JS -->
                                </div>
                            </div>
                        </div>
                    </div>
                @else
                    <div class="text-center py-5">
                        <i class="fas fa-calendar-times fa-3x text-muted mb-3"></i>
                        <h5 class="text-muted">No Tasks Available</h5>
                        <p class="text-muted">Tasks will appear here once they are created and assigned.</p>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>


@section('styles')
<style>
.timeline-section {
    margin-top: 2rem;
}

.project-overview {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 1.5rem;
    border-radius: 10px;
    margin-bottom: 1.5rem;
}

.job-meta {
    margin-top: 0.5rem;
}

.progress-circle {
    width: 80px;
    height: 80px;
    background: conic-gradient(#ffffff {{ $jobStats['overall_progress'] * 3.6 }}deg, rgba(255,255,255,0.3) 0deg);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-left: auto;
}

.progress-circle .progress-text {
    background: rgba(255,255,255,0.2);
    padding: 0.5rem;
    border-radius: 50%;
    font-weight: bold;
    font-size: 0.9rem;
}

.date-controls {
    background: #f8f9fa;
    padding: 1rem;
    border-radius: 8px;
}

.timeline-chart {
    border: 1px solid #dee2e6;
    border-radius: 8px;
    overflow: hidden;
}

.timeline-header {
    display: flex;
    background: #f8f9fa;
    border-bottom: 2px solid #dee2e6;
    position: sticky;
    top: 0;
    z-index: 10;
}

.timeline-labels {
    width: 250px;
    min-width: 250px;
    padding: 1rem;
    font-weight: 600;
    border-right: 2px solid #dee2e6;
    background: #f8f9fa;
}

.timeline-dates-container {
    flex: 1;
    overflow-x: auto;
    background: #f8f9fa;
}

.timeline-dates {
    display: flex;
    height: 50px;
    min-width: max-content;
}

.date-column {
    min-width: 60px;
    width: 60px;
    flex-shrink: 0;
    padding: 0.5rem 0.25rem;
    text-align: center;
    border-right: 1px solid #e9ecef;
    font-size: 0.8rem;
}

.date-column.today {
    background: #fff3cd;
    font-weight: bold;
}

.date-column.weekend {
    background: #f8f9fa;
    color: #6c757d;
}

.timeline-content {
    max-height: 500px;
    overflow-y: auto;
}

.timeline-row {
    display: flex;
    min-height: 70px; /* Increased for duration text */
    border-bottom: 1px solid #f0f0f0;
    cursor: pointer;
    transition: background 0.2s;
}

.timeline-row:hover {
    background: #f8f9fa;
}

.timeline-row.selected {
    background: #e3f2fd;
    border-left: 4px solid #2196f3;
}

.task-label {
    width: 250px;
    min-width: 250px;
    padding: 1rem;
    border-right: 2px solid #dee2e6;
    display: flex;
    align-items: center;
    background: white;
}

.task-info {
    display: flex;
    align-items: center;
    width: 100%;
}

.task-name {
    font-weight: 600;
    margin-bottom: 0.25rem;
}

.task-users {
    font-size: 0.8rem;
    color: #6c757d;
    margin-bottom: 0.25rem;
}

/* ADDED: Duration styling */
.task-duration {
    font-size: 0.75rem;
    color: #6c757d;
}

.task-timeline-container {
    flex: 1;
    overflow-x: auto;
}

.task-timeline {
    padding: 1rem;
    position: relative;
    min-width: max-content;
}

.task-bar {
    height: 30px;
    border-radius: 15px;
    position: absolute;
    overflow: hidden;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    min-width: 60px;
}

.task-completed {
    background: linear-gradient(135deg, #28a745, #20c997);
}

.task-progress {
    background: linear-gradient(135deg, #007bff, #6610f2);
}

.task-pending {
    background: linear-gradient(135deg, #ffc107, #fd7e14);
}

.task-content {
    display: flex;
    align-items: center;
    padding: 0 0.75rem;
    height: 100%;
    color: white;
    font-weight: 600;
    font-size: 0.85rem;
    position: relative;
}

.progress-fill {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    background: rgba(255,255,255,0.3);
    border-radius: 15px;
}

.extension-badge {
    position: absolute;
    top: -5px;
    right: -5px;
    background: #dc3545;
    color: white;
    border-radius: 50%;
    width: 20px;
    height: 20px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.7rem;
}

/* ADDED: Time indicators */
.time-indicator {
    position: absolute;
    top: -8px;
    background: rgba(0,0,0,0.8);
    color: white;
    border-radius: 50%;
    width: 16px;
    height: 16px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.6rem;
}

.time-indicator.start-time {
    left: -8px;
}

.time-indicator.end-time {
    right: -8px;
}

.today-marker {
    position: absolute;
    top: 0;
    bottom: 0;
    width: 2px;
    background: #dc3545;
    z-index: 5;
    pointer-events: none;
}

.task-details {
    margin-top: 1.5rem;
    padding: 1rem;
    background: #f8f9fa;
    border-radius: 8px;
}

.timeline-scroll-container {
    overflow-x: auto;
    overflow-y: hidden;
    width: 100%;
}

.timeline-header,
.timeline-content {
    min-width: max-content;
    overflow: visible !important;
}

.timeline-content {
    max-height: none !important;
    overflow-y: visible !important;
}

.timeline-dates-container,
.task-timeline-container {
    overflow-x: visible !important;
    overflow-y: visible !important;
}

.timeline-dates-container::-webkit-scrollbar,
.task-timeline-container::-webkit-scrollbar {
    height: 8px;
}

.timeline-dates-container::-webkit-scrollbar-track,
.task-timeline-container::-webkit-scrollbar-track {
    background: #f1f1f1;
    display: none;
}

.timeline-dates-container::-webkit-scrollbar-thumb,
.task-timeline-container::-webkit-scrollbar-thumb {
    background: #888;
    border-radius: 4px;
}

.timeline-dates-container::-webkit-scrollbar-thumb:hover,
.task-timeline-container::-webkit-scrollbar-thumb:hover {
    background: #555;
}

.alert-sm {
    padding: 0.5rem 1rem;
    font-size: 0.875rem;
}
</style>
@endsection

<script>
const jobId = {{ $job->id }};
const tasksData = @json($timelineData['tasks'] ?? []);

document.addEventListener('DOMContentLoaded', function() {
    @if(count($timelineData['tasks']) > 0)
        initTimeline();
        setupScrollSync();
    @endif
});

function initTimeline() {
    generateDates();
    positionTasks();
    addTodayMarker();
    checkScrollNeed();
}

function generateDates() {
    const container = document.getElementById('timelineDates');
    if (!container) return;

    const startDate = new Date(document.getElementById('startDate').value);
    const endDate = new Date(document.getElementById('endDate').value);
    const today = new Date();

    container.innerHTML = '';
    let current = new Date(startDate);

    while (current <= endDate) {
        const col = document.createElement('div');
        col.className = 'date-column';

        const day = current.getDate();
        const month = current.toLocaleDateString('en', { month: 'short' });

        if (current.toDateString() === today.toDateString()) {
            col.classList.add('today');
        }
        if (current.getDay() === 0 || current.getDay() === 6) {
            col.classList.add('weekend');
        }

        col.innerHTML = `<div style="font-size: 0.7rem; color: #6c757d;">${month}</div><div>${day}</div>`;
        container.appendChild(col);

        current.setDate(current.getDate() + 1);
    }
}

function positionTasks() {
    const startDate = new Date(document.getElementById('startDate').value);
    const endDate = new Date(document.getElementById('endDate').value);
    const totalDays = Math.ceil((endDate - startDate) / (1000 * 60 * 60 * 24)) + 1;
    const dayWidth = 60;

    // Set the width of each task timeline
    document.querySelectorAll('.task-timeline').forEach(timeline => {
        timeline.style.width = (totalDays * dayWidth) + 'px';
    });

    document.querySelectorAll('.timeline-row').forEach(row => {
        const taskBar = row.querySelector('.task-bar');
        if (!taskBar) return;

        // UPDATED: Use original task dates (not when user actually started)
        const taskStart = taskBar.dataset.start ? new Date(taskBar.dataset.start) : null;
        const taskEnd = taskBar.dataset.end ? new Date(taskBar.dataset.end) : null;

        // Hide tasks completely outside the date range
        if (!taskStart || !taskEnd || taskEnd < startDate || taskStart > endDate) {
            row.style.display = 'none';
            return;
        }

        // Show tasks that fall within or overlap the range
        row.style.display = 'flex';

        // UPDATED: Calculate position in pixels using ORIGINAL task dates
        const effectiveStart = new Date(Math.max(taskStart, startDate));
        const effectiveEnd = new Date(Math.min(taskEnd, endDate));

        const startOffset = Math.ceil((effectiveStart - startDate) / (1000 * 60 * 60 * 24));
        const duration = Math.ceil((effectiveEnd - effectiveStart) / (1000 * 60 * 60 * 24)) + 1;

        const leftPx = startOffset * dayWidth;
        const widthPx = Math.max(duration * dayWidth, 60); // Minimum 60px width

        taskBar.style.left = leftPx + 'px';
        taskBar.style.width = widthPx + 'px';
        taskBar.style.position = 'absolute';
    });
}

function addTodayMarker() {
    const startDate = new Date(document.getElementById('startDate').value);
    const endDate = new Date(document.getElementById('endDate').value);
    const today = new Date();
    const dayWidth = 60;

    document.querySelectorAll('.today-marker').forEach(m => m.remove());

    if (today >= startDate && today <= endDate) {
        const dayOffset = Math.ceil((today - startDate) / (1000 * 60 * 60 * 24));
        const leftPx = dayOffset * dayWidth;

        document.querySelectorAll('.task-timeline').forEach(timeline => {
            const marker = document.createElement('div');
            marker.className = 'today-marker';
            marker.style.left = leftPx + 'px';
            timeline.appendChild(marker);
        });
    }
}

function checkScrollNeed() {
    const datesContainer = document.querySelector('.timeline-dates-container');
    const datesContent = document.querySelector('.timeline-dates');
    const instructions = document.getElementById('scrollInstructions');

    if (datesContainer && datesContent && instructions) {
        if (datesContent.scrollWidth > datesContainer.clientWidth) {
            instructions.style.display = 'block';
        } else {
            instructions.style.display = 'none';
        }
    }
}

function setupScrollSync() {
    const datesContainer = document.querySelector('.timeline-dates-container');
    const taskContainers = document.querySelectorAll('.task-timeline-container');

    if (!datesContainer) return;

    datesContainer.addEventListener('scroll', function() {
        taskContainers.forEach(container => {
            container.scrollLeft = this.scrollLeft;
        });
    });

    taskContainers.forEach(container => {
        container.addEventListener('scroll', function() {
            datesContainer.scrollLeft = this.scrollLeft;
            taskContainers.forEach(otherContainer => {
                if (otherContainer !== this) {
                    otherContainer.scrollLeft = this.scrollLeft;
                }
            });
        });
    });
}

function selectTask(taskId) {
    // Remove previous selection
    document.querySelectorAll('.timeline-row').forEach(row => {
        row.classList.remove('selected');
    });

    // Add selection to current row
    const selectedRow = document.querySelector(`[data-task-id="${taskId}"]`);
    if (selectedRow) {
        selectedRow.classList.add('selected');
    }

    // Fetch and display task details
    fetch(`/jobs/${jobId}/tasks/${taskId}/details`)
        .then(response => response.json())
        .then(data => {
            displayTaskDetails(data);
        })
        .catch(error => {
            console.error('Error fetching task details:', error);
        });
}

function displayTaskDetails(data) {
    const panel = document.getElementById('taskDetails');

    // Update task info
    document.getElementById('taskName').textContent = data.task.name;
    document.getElementById('taskDescription').textContent = data.task.description;

    // UPDATED: Timeline info with time components
    if (data.users.length > 0) {
        const user = data.users[0];
        let timelineText = 'Not set';

        if (user.start_date && user.end_date) {
            const startDate = new Date(user.start_date).toLocaleDateString();
            const endDate = new Date(user.end_date).toLocaleDateString();

            // Add time if available
            if (user.start_time && user.end_time) {
                timelineText = `${startDate} ${user.start_time} - ${endDate} ${user.end_time}`;
            } else {
                timelineText = `${startDate} - ${endDate}`;
            }
        }

        document.getElementById('taskTimeline').textContent = timelineText;

        // Duration and time remaining
        if (user.formatted_duration) {
            document.getElementById('taskPlannedDuration').textContent = user.formatted_duration;
        }

        // Calculate time remaining
        if (user.end_date && user.end_time) {
            const endDateTime = new Date(`${user.end_date} ${user.end_time || '23:59:59'}`);
            const now = new Date();

            if (endDateTime > now) {
                const diffMs = endDateTime - now;
                const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
                const diffHours = Math.floor((diffMs % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));

                let remaining = '';
                if (diffDays > 0) remaining += `${diffDays}d `;
                if (diffHours > 0) remaining += `${diffHours}h`;

                document.getElementById('taskTimeRemaining').textContent = remaining || 'Less than 1h';
            } else {
                document.getElementById('taskTimeRemaining').textContent = 'Overdue';
            }
        }
    }

    // Update progress
    const progressBar = document.getElementById('taskProgressBar');
    const progressText = document.getElementById('taskProgressText');
    progressBar.style.width = data.task.progress + '%';
    progressText.textContent = data.task.progress + '%';

    // Update users
    const usersContainer = document.getElementById('taskUsers');
    usersContainer.innerHTML = '';
    data.users.forEach(user => {
        const userDiv = document.createElement('div');
        userDiv.className = 'badge bg-secondary me-2 mb-1';
        userDiv.innerHTML = `${user.name} <small>(${user.status})</small>`;
        usersContainer.appendChild(userDiv);
    });

    panel.style.display = 'block';
}

function updateDateRange() {
    initTimeline();
}

function setQuickRange(type) {
    const startInput = document.getElementById('startDate');
    const endInput = document.getElementById('endDate');
    const today = new Date();

    // Update button states
    document.querySelectorAll('.btn-group .btn').forEach(btn => btn.classList.remove('active'));
    event.target.classList.add('active');

    switch(type) {
        case 'week':
            const weekStart = new Date(today);
            weekStart.setDate(today.getDate() - today.getDay());
            const weekEnd = new Date(weekStart);
            weekEnd.setDate(weekStart.getDate() + 6);
            startInput.value = weekStart.toISOString().split('T')[0];
            endInput.value = weekEnd.toISOString().split('T')[0];
            break;
        case 'month':
            const monthStart = new Date(today.getFullYear(), today.getMonth(), 1);
            const monthEnd = new Date(today.getFullYear(), today.getMonth() + 1, 0);
            startInput.value = monthStart.toISOString().split('T')[0];
            endInput.value = monthEnd.toISOString().split('T')[0];
            break;
        case 'job':
            // UPDATED: Use full timeline dates from PHP data
            startInput.value = '{{ $timelineData["timeline_start"] ? $timelineData["timeline_start"]->format("Y-m-d") : ($job->start_date ? $job->start_date->format("Y-m-d") : date("Y-m-d")) }}';
            endInput.value = '{{ $timelineData["timeline_end"] ? $timelineData["timeline_end"]->format("Y-m-d") : ($job->due_date ? $job->due_date->format("Y-m-d") : date("Y-m-d", strtotime("+30 days"))) }}';
            break;
    }

    initTimeline();
}

function refreshTimeline() {
    fetch(`/jobs/${jobId}/timeline-data`)
        .then(response => response.json())
        .then(data => {
            location.reload(); // Simple reload for now
        })
        .catch(error => console.error('Error:', error));
}
</script>
